# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='cityName')),
                ('desc', models.CharField(max_length=200, verbose_name='description')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
            ],
            options={
                'verbose_name': 'CityDict',
                'verbose_name_plural': 'CityDict',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='orgName')),
                ('desc', models.TextField(verbose_name='description')),
                ('clickNum', models.IntegerField(default=0, verbose_name='clickNum')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('favoriteNum', models.IntegerField(default=0, verbose_name='favoriteNum')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to='organization/%Y/%m', verbose_name='pageImage')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='city')),
            ],
            options={
                'verbose_name': 'CourseOrg',
                'verbose_name_plural': 'CourseOrg',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='teacherName')),
                ('workYears', models.IntegerField(default=0, verbose_name='workYears')),
                ('workCompany', models.CharField(max_length=50, verbose_name='workCompany')),
                ('level', models.CharField(max_length=50, verbose_name='level')),
                ('features', models.CharField(max_length=100, verbose_name='features')),
                ('favoriteNum', models.IntegerField(default=0, verbose_name='favoriteNum')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='courseOrg')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher',
            },
        ),
    ]
