# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('company', 'company'), ('univeristy', 'univeristy')], default='company', max_length=20, verbose_name='category'),
        ),
    ]
