# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='studentsNum',
            field=models.IntegerField(default=0, verbose_name='studentNum'),
        ),
    ]
