# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorg_studentsnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='studentsNum',
            new_name='studentNum',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='courseNum',
            field=models.IntegerField(default=0, verbose_name='courseNum'),
        ),
    ]
