# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180102_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/%Y/%m', verbose_name='photo'),
        ),
    ]
