# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 21:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='comments')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'CourseComments',
                'verbose_name_plural': 'CourseComments',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('mobile', models.CharField(max_length=11, verbose_name='mobile')),
                ('courseName', models.CharField(max_length=50, verbose_name='courseName')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
            ],
            options={
                'verbose_name': 'UserAsk',
                'verbose_name_plural': 'UserAsk',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'UserCourse',
                'verbose_name_plural': 'UserCourse',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataId', models.IntegerField(default=0, verbose_name='dataId')),
                ('dataType', models.IntegerField(choices=[(1, 'class'), (2, 'courseOrganization'), (3, 'teacher')], default=1, verbose_name='dataType')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'UserFavorite',
                'verbose_name_plural': 'UserFavorite',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='userId')),
                ('message', models.CharField(max_length=500, verbose_name='message')),
                ('hasRead', models.BooleanField(default=False, verbose_name='hasRead')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
            ],
            options={
                'verbose_name': 'UserMessage',
                'verbose_name_plural': 'UserMessage',
            },
        ),
    ]
