# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='courseName')),
                ('desc', models.CharField(max_length=300, verbose_name='description')),
                ('detail', models.TextField(verbose_name='courseDetail')),
                ('degree', models.CharField(choices=[('primary', 'primary'), ('middle', 'middle'), ('senior', 'senior')], default='primary', max_length=20, verbose_name='degree')),
                ('learnTime', models.IntegerField(default=0, verbose_name='learnTime')),
                ('studentsNum', models.IntegerField(default=0, verbose_name='studentsNum')),
                ('favoriteNum', models.IntegerField(default=0, verbose_name='favoriteNum')),
                ('image', models.ImageField(upload_to='course/%Y/%m', verbose_name='pageImage')),
                ('clickNum', models.IntegerField(default=0, verbose_name='clickNum')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ResourceName')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='resourceAddress')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'CourseResource',
                'verbose_name_plural': 'CourseResource',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='LessonName')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lesson',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='VideoName')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='lesson')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
            },
        ),
    ]
