# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='studentsNum',
        ),
        migrations.AddField(
            model_name='course',
            name='studentNum',
            field=models.IntegerField(default=0, verbose_name='studentNum'),
        ),
    ]
