# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='verifyCode')),
                ('email', models.EmailField(max_length=50, verbose_name='emailBox')),
                ('sendType', models.CharField(choices=[('register', 'register'), ('forget', 'forget')], max_length=10)),
                ('sendTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='sendTime')),
            ],
            options={
                'verbose_name': 'EmailVerifyCode',
                'verbose_name_plural': 'EmailVerifyCode',
            },
        ),
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='image')),
                ('url', models.URLField(verbose_name='url')),
                ('index', models.IntegerField(default=100, verbose_name='index')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='addTime')),
            ],
            options={
                'verbose_name': 'PageBanner',
                'verbose_name_plural': 'PageBanner',
            },
        ),
    ]
